# theme: hyprland-dark-teal
background              #181818
foreground              #ffffff
cursor                  #ffffff
cursor_text_color       #000000
selection_foreground    #ffffff
selection_background    #262626
active_tab_background   #1a1a1a
active_tab_foreground   #ffffff
inactive_tab_background #111111
inactive_tab_foreground #888888
