# theme: blasphemous-mea-culpa
background              #110f0d
foreground              #e7eeed
cursor                  #e7eeed
cursor_text_color       #110f0d
selection_foreground    #e7eeed
selection_background    #413730
active_tab_background   #241d19
active_tab_foreground   #e7eeed
inactive_tab_background #0c0b0a
inactive_tab_foreground #8b9795

background_opacity 0.65
