# theme: blashphemous-II-the-third-sin
background              #171e26
foreground              #ffffff
cursor                  #a0c3bc
cursor_text_color       #000000
selection_foreground    #ffffff
selection_background    #252e3a
active_tab_background   #1a222c
active_tab_foreground   #a0c3bc
inactive_tab_background #11181e
inactive_tab_foreground #6a7a7e

background_opacity 0.65
