# theme: blasphemous-ten-piedad
background              #1c1c1f
foreground              #d4ccb0
cursor                  #c8a863
cursor_text_color       #1c1c1f
selection_foreground    #1c1c1f
selection_background    #c8a863
active_tab_background   #242226
active_tab_foreground   #c8a863
inactive_tab_background #141416
inactive_tab_foreground #6a6258

# Black
color0  #1c1c1f
color8  #45342f
# Red
color1  #7a4a44
color9  #8a6058
# Green
color2  #a09670
color10 #b0a680
# Yellow
color3  #c8a863
color11 #d4b878
# Blue
color4  #4a5260
color12 #607080
# Magenta
color5  #5a4252
color13 #7a5a6a
# Cyan
color6  #5a6a62
color14 #7a8a82
# White
color7  #90887e
color15 #d4ccb0

background_opacity 0.65
