# HyprAshen theme for Bottom

[color]
background = "#181818"
foreground = "#757575"
border = "#757575"
text = "#757575"
selected_text = "#181818"
selected_bg = "#757575"

[colors]
cpu_color = "#757575"
mem_color = "#757575"
swap_color = "#333333"
rx_color = "#757575"
tx_color = "#757575"
rx_total_color = "#333333"
tx_total_color = "#757575"
process_color = "#757575"
process_highlighted_color = "#757575"
average_cpu_color = "#757575"
