# Blasphemous II - Repose of the Silent One theme for Bottom

[color]
# Overall theme
background = "#141e1e"
foreground = "#d8e0de"

# Specific UI elements
border = "#5a8a8a"
text = "#d8e0de"
selected_text = "#141e1e"
selected_bg = "#5a8a8a"

[colors]
cpu_color = "#5a9a7a"
mem_color = "#5a8a9a"
swap_color = "#8a5a5a"
rx_color = "#5a9a9a"
tx_color = "#5a9a7a"
rx_total_color = "#5a8a9a"
tx_total_color = "#5a9a9a"
process_color = "#d8e0de"
process_highlighted_color = "#8ac0d0"
average_cpu_color = "#7a9a9a"
