# theme: blasphemous-penitent
background              #000000
foreground              #e0e0e0
cursor                  #e0e0e0
cursor_text_color       #000000
selection_foreground    #000000
selection_background    #e0e0e0
active_tab_background   #0a0a0a
active_tab_foreground   #e0e0e0
inactive_tab_background #050505
inactive_tab_foreground #666666

color0  #000000
color8  #1a1a1a
color1  #e0e0e0
color9  #e0e0e0
color2  #e0e0e0
color10 #e0e0e0
color3  #e0e0e0
color11 #e0e0e0
color4  #e0e0e0
color12 #e0e0e0
color5  #e0e0e0
color13 #e0e0e0
color6  #e0e0e0
color14 #e0e0e0
color7  #808080
color15 #e0e0e0

background_opacity 0.80
