# Minimal theme for Bottom

[color]
background = "#2F3541"
foreground = "#A6B8C4"
border = "#3B4352"
text = "#A6B8C4"
selected_text = "#2F3541"
selected_bg = "#7492A7"

[colors]
cpu_color = "#7492A7"
mem_color = "#A6B8C4"
swap_color = "#545C69"
rx_color = "#A6B8C4"
tx_color = "#7492A7"
rx_total_color = "#545C69"
tx_total_color = "#A6B8C4"
process_color = "#A6B8C4"
process_highlighted_color = "#7492A7"
average_cpu_color = "#A6B8C4"
