# theme: blasphemous-II-red-forest
background              #d9d1d2
foreground              #2a282c
cursor                  #3d2932
cursor_text_color       #d9d1d2
selection_foreground    #d9d1d2
selection_background    #3d2932
active_tab_background   #c8c0c2
active_tab_foreground   #2a282c
inactive_tab_background #e3ddde
inactive_tab_foreground #7c7578

# Black
color0  #3d3538
color8  #7c7578
# Red
color1  #8a4048
color9  #a86060
# Green
color2  #3d2932
color10 #5a424a
# Yellow
color3  #9b7d35
color11 #b89640
# Blue
color4  #5a5a7a
color12 #707090
# Magenta
color5  #7a5a6a
color13 #9a7a8a
# Cyan
color6  #6a7a7e
color14 #8a9a9e
# White
color7  #c0b8ba
color15 #e3ddde

background_opacity 0.65
