# theme: blasphemous-requiem-aeternam
background              #000000
foreground              #ba8540
cursor                  #ba8540
cursor_text_color       #000000
selection_foreground    #000000
selection_background    #ba8540
active_tab_background   #0a0805
active_tab_foreground   #ba8540
inactive_tab_background #050502
inactive_tab_foreground #5a4020

color0  #000000
color8  #1a1510
color1  #ba8540
color9  #ba8540
color2  #ba8540
color10 #ba8540
color3  #ba8540
color11 #ba8540
color4  #ba8540
color12 #ba8540
color5  #ba8540
color13 #ba8540
color6  #ba8540
color14 #ba8540
color7  #6a4a20
color15 #ba8540

background_opacity 0.65
