# Qt apps native on Wayland
QT_QPA_PLATFORM=wayland

# Firefox native
MOZ_ENABLE_WAYLAND=1

# Electron (VSCode, Discord, Obsidian...)
ELECTRON_OZONE_PLATFORM_HINT=auto

# SDL2 (games, emulators)
SDL_VIDEODRIVER=wayland

# Java (JetBrains, Android Studio)
_JAVA_AWT_WM_NONREPARENTING=1

# LibreOffice
SAL_USE_VCLPLUGIN=gtk3

# Cursor
XCURSOR_THEME=Adwaita
XCURSOR_SIZE=24

# Identification session
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=Hyprland
XDG_CURRENT_DESKTOP=Hyprland

LC_ALL=pt_BR.UTF-8
LANGUAGE=pt_BR:en

XKBLAYOUT=br
XKBVARIANT=abnt2
