# theme: blasphemous-kneeling-stone
background              #1e1e2e
foreground              #cdd6f4
cursor                  #f5e0dc
cursor_text_color       #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc
active_tab_background   #cba6f7
active_tab_foreground   #1e1e2e
inactive_tab_background #313244
inactive_tab_foreground #bac2de
