# theme: hyprashen
background              #181818
foreground              #a2a2a2
cursor                  #a2a2a2
cursor_text_color       #181818
selection_foreground    #181818
selection_background    #a2a2a2
active_tab_background   #a2a2a2
active_tab_foreground   #141414
inactive_tab_background #181818
inactive_tab_foreground #7f7f7f

background_opacity 0.65
