# theme: blasphemous-fragment-of-guilt
background              #282826
foreground              #d8e0de
cursor                  #89b1a9
cursor_text_color       #282826
selection_foreground    #282826
selection_background    #89b1a9
active_tab_background   #303230
active_tab_foreground   #89b1a9
inactive_tab_background #222220
inactive_tab_foreground #6a7a76

# Black
color0  #282826
color8  #495553
# Red
color1  #c45a52
color9  #d87068
# Green
color2  #67837b
color10 #89b1a9
# Yellow
color3  #948f67
color11 #b0a878
# Blue
color4  #5a6a7a
color12 #708090
# Magenta
color5  #7a5a6a
color13 #9a7a8a
# Cyan
color6  #5a8a82
color14 #7aaaa2
# White
color7  #a0b0ac
color15 #d8e0de

background_opacity 0.65
