# theme: blasphemous-fragment-of-guilt
background              #eef7f4
foreground              #24302e
cursor                  #24302e
cursor_text_color       #0a0a07
selection_foreground    #24302e
selection_background    #cfe4df
active_tab_background   #dfece8
active_tab_foreground   #24302e
inactive_tab_background #f7fbf9
inactive_tab_foreground #0a0a07
