# Blasphemous II - Red Forest theme for Bottom

[color]
background = "#d9d1d2"
foreground = "#2a282c"
border = "#3d2932"
text = "#2a282c"
selected_text = "#d9d1d2"
selected_bg = "#3d2932"

[colors]
cpu_color = "#3d2932"
mem_color = "#5a5a7a"
swap_color = "#8a4048"
rx_color = "#5a424a"
tx_color = "#3d2932"
rx_total_color = "#7c7578"
tx_total_color = "#5a424a"
process_color = "#2a282c"
process_highlighted_color = "#5a424a"
average_cpu_color = "#5a424a"
