# ===================================
#  Hyprlock 0.9+
#  File: ~/.config/hypr/hyprlock.conf
#  By: William C. Canin
# ===================================

background {
  monitor =
  path = ~/.cache/hypr/hyprlock-wallpaper-blur.png
  blur_size = 3
  blur_passes = 3
  brightness = 0.92
}

input-field {
  monitor =
  size = 280 45
  font_size = 14
  outline_thickness = 1
  outer_color = rgb(5aa59d)
  inner_color = rgb(eef7f4)
  font_color = rgb(24302e)
  placeholder_text = <i>  Password</i>
  position = 0, -100
  halign = center
  valign = center
  rounding = 6
}

shape {
  monitor =
  size = 320, 150
  color = rgba(238, 247, 244, 0.70)
  rounding = 12
  position = 0, 83
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(36, 48, 46, 0.88)
  font_size = 64
  font_family = JetBrainsMono Nerd Font
  position = 0, 100
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %d %B"
    color = rgba(36, 48, 46, 0.78)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}
