# ===================================
#  Hyprpaper 0.8+
#  File: ~/.config/hypr/hyprpaper.conf
#  By: William C. Canin
# ===================================

wallpaper {
  monitor =
  path =  ~/.config/hypr/wallpapers/minimal.png
  fit_mode = cover
}

## Disable splash (text random) in wallpaper
splash = false
