# ===================================
#  Hyprlock 0.9+
#  File: ~/.config/hypr/hyprlock.conf
#  By: William C. Canin
# ===================================

background {
  monitor =
  path = ~/.cache/hypr/hyprlock-wallpaper-blur.png
  blur_size = 3
  blur_passes = 3
  brightness = 0.7
}

input-field {
  monitor =
  size = 280, 45
  outline_thickness = 1
  outer_color = rgb(3aa99f)
  inner_color = rgb(181818)
  font_color = rgb(ffffff)
  placeholder_text = <i>  Password</i>
  position = 0, -100
  halign = center
  valign = center
  rounding = 6
}

shape {
  monitor =
  size = 320, 150
  color = rgba(10, 30, 25, 0.55)
  rounding = 12
  position = 0, 83
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 64
  font_family = JetBrainsMono Nerd Font
  position = 0, 100
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %d %B"
    color = rgba(255, 255, 255, 0.8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}
