general {
  lock_cmd = sh ~/.config/hypr/scripts/power-menu.sh --lock
  before_sleep_cmd = sh ~/.config/hypr/scripts/power-menu.sh --lock
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 300
  on-timeout = sh ~/.config/hypr/scripts/power-menu.sh --lock
}

## -- Disable/Enable monitor with timeout ---------------------------------------
# listener {
#     timeout = 600
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }
